name: Publish Rock to Registry
description: Publishes a Rock package to the GHCR registry
inputs:
  rock:
    description: Path to a .rock file
    required: true
  username:
    description: Username to use for the registry
    required: true
  password:
    description: Password to use for the registry
    required: true
runs:
  using: composite
  steps:
    - name: Install skopeo
      shell: bash
      run: |
        sudo apt update
        sudo apt install -y skopeo
    - name: Install yq
      shell: bash
      run: sudo snap install yq
    - name: Log in to the Container registry
      shell: bash
      run: |
        skopeo login ghcr.io --username "${{ inputs.username }}"" --password "${{ inputs.password }}"
    - name: Import and push to github package
      shell: bash
      run: |
        rock_file="${{ inputs.rock }}"
        rockdir=$(dirname $rock_file)
        image_name="$(yq '.name' $rockdir/rockcraft.yaml)"
        version="$(yq '.version' $rockdir/rockcraft.yaml)"
        echo "Publishing rock ${image_name}:${version}"
        sudo skopeo \
          --insecure-policy \
          copy \
          oci-archive:"${rock_file}" \
          docker://"ghcr.io/canonical/${image_name}:${version}"
    - name: Log out of the Container registry
      if: always()
      shell: bash
      run: |
        skopeo logout ghcr.io
