name: Push

on:
  workflow_call:
    inputs:
        rocks:
            description: List of rocks to build
            required: true
            type: string
            default: '[]'
        publish:
            description: Publish rocks ?
            default: false
            type: boolean
        branch:
            description: Branch to build from
            default: main
            type: string

jobs:
  build-and-publish:
    if: ${{ inputs.rocks != '[]' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rock: ${{ fromJson(inputs.rocks) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
      - name: Setup LXD
        uses: canonical/setup-lxd@v0.1.1
        with:
          channel: 5.21/candidate
      - uses: canonical/craft-actions/rockcraft-pack@1de2f7678b7ecfd491bd8ec3c2d2f73fe722c643
        id: rockcraft
        with:
          path: rocks/${{ matrix.rock }}
      - uses: ./.github/actions/publish-rock
        if: ${{ inputs.publish }}
        with:
          rock: ${{ steps.rockcraft.outputs.rock }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
