name: Pull Request

on:
 pull_request:
    paths:
      - "rocks/*/rockcraft.yaml"
      - ".github/workflows/**.yaml"

jobs:
  changedfiles:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      rocks: ${{ steps.changes.outputs.rocks }}
    steps:
        # Make sure we have some code to diff.
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Get changed files
        id: changes
        # Set outputs using the command.
        run: |
          echo "rocks=$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep rockcraft.yaml | sed 's/\(\S.*\)\/rockcraft.yaml/\1/')" >> $GITHUB_OUTPUT
  build:
    # only run if any rockcraft.yaml changes
    if: ${{needs.changedfiles.outputs.rocks}}
    strategy:
      matrix:
        service: ${{needs.changedfiles.outputs.rocks}}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: canonical/craft-actions/rockcraft-pack@main
        id: rockcraft
        with:
          inputs: ${{ matrix.service }}
      - uses: actions/upload-artifact@v3
        with:
          name: rock
          path: ${{ steps.rockcraft.outputs.rock }}
