name: Push

on:
  push:
    branches:
      - main
      - stable/2023.1

jobs:
  build:
    uses: ./.github/workflows/build.yaml

  publish:
    needs: build
    uses: ./.github/workflows/publish.yaml
